import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "@/components/ui/toaster";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "jos-animation/dist/jos.css";
import "swiper/css";
import "swiper/css/navigation";
import "@/styles/globals.css";

// Load Inter font
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

// Load Futuru font
const futuru = localFont({
  src: [
    {
      path: "../fonts/Futuru-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../fonts/Futuru-ExtraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../fonts/Futuru-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/Futuru-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Futuru-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Futuru-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/Futuru-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/Futuru-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../fonts/Futuru-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-futuru",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${inter.variable} ${futuru.variable}`}>
        <body className="font-inter">
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
